ALTER TABLE users ADD COLUMN pix_key VARCHAR(255);
ALTER TABLE users ADD COLUMN bank_name VARCHAR(255);
ALTER TABLE users ADD COLUMN bank_agency VARCHAR(50);
ALTER TABLE users ADD COLUMN bank_account VARCHAR(50);
ALTER TABLE users ADD COLUMN account_type VARCHAR(50); -- CORRENTE, POUPANCA
